project 'SwpGuidancePageDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'SwpGuidancePageDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SwpGuidancePageDemo
  inhibit_all_warnings!

  pod 'SwpGuidancePage', :path => '../'

end
