project 'SwpGuidancePageDemo.xcodeproj'
  source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwpGuidancePageDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SwpGuidancePageDemo
  inhibit_all_warnings!

  pod 'SwpGuidancePage', :path => '../'

end
